### ISSUE TITLE
Polymorphic deserialization issues with kotlinx.serialization

### ISSUE THREAD

**Issue by mtorials** [benkuly/trixnity#1]
Hi!

I read about your Kotlin lib on matrix.org and I wanted to check it out as I am currently writing a Kotlin lib for matrix myself. It is for the jvm but I started to port it to Kotlin multiplatform and wanted to switch from Jackson to kotlinx. But I encountered some issues with this library.
Kotlinx.multiplatform does not support multiple type discriminators for polymorphism as discussed in this [issue](https://github.com/Kotlin/kotlinx.serialization/issues/546)(It is interestingly also matrix cs-api related). But the matrix API relies uses "type" in most cases, but in other cases "errcode" and "msgtype". I am not very familiar with kotlinx.serialization but I did not find a nice way around this problem so I stopped working on my kotlinx branch for the moment.

I am just interested in your thoughts on this.

**Comment by benkuly** [comment]
I use `JsonContentPolymorphicSerializer` for it. Have a look into [this package](https://github.com/benkuly/trixnity/tree/main/trixnity-core/src/commonMain/kotlin/net/folivo/trixnity/core/serialization). If you have more questions feel free to ask them in https://matrix.to/#/#trixnity:imbitbu.de
